table Matches
	lineageTag: 01468402-4de4-4042-a980-474ce902c070

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 70bb2922-4135-4871-a231-01b7c31a1e2c
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: cf10095c-46d6-4d1e-96e0-2d221d0aba1e
			defaultHierarchy: LocalDateTable_f5eb13b9-5ec5-465c-8223-ac32ef7f6da8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HomeTeam
		dataType: string
		lineageTag: a604c221-a886-4910-a088-890c609f59ac
		summarizeBy: none
		sourceColumn: HomeTeam

		annotation SummarizationSetBy = Automatic

	column AwayTeam
		dataType: string
		lineageTag: 4c6089bd-0234-4adc-a13e-dd6c9e984207
		summarizeBy: none
		sourceColumn: AwayTeam

		annotation SummarizationSetBy = Automatic

	column FTHG
		dataType: int64
		formatString: 0
		lineageTag: 46668ec1-4583-48f2-a120-92c2b0e84e1d
		summarizeBy: sum
		sourceColumn: FTHG

		annotation SummarizationSetBy = Automatic

	column FTAG
		dataType: int64
		formatString: 0
		lineageTag: 396a2a60-fb61-475f-8649-e4e3005aafdc
		summarizeBy: sum
		sourceColumn: FTAG

		annotation SummarizationSetBy = Automatic

	column FTR
		dataType: string
		lineageTag: a769bff0-5405-4791-8ca9-09eb78557b3a
		summarizeBy: none
		sourceColumn: FTR

		annotation SummarizationSetBy = Automatic

	column HTHG
		dataType: int64
		formatString: 0
		lineageTag: 5a08402b-d07c-4004-b618-c43c799fef98
		summarizeBy: sum
		sourceColumn: HTHG

		annotation SummarizationSetBy = Automatic

	column HTAG
		dataType: int64
		formatString: 0
		lineageTag: cedf7dd2-3887-4486-b694-5d26274e1004
		summarizeBy: sum
		sourceColumn: HTAG

		annotation SummarizationSetBy = Automatic

	column HTR
		dataType: string
		lineageTag: 9d97d09b-1c17-4609-9444-87af4e6df493
		summarizeBy: none
		sourceColumn: HTR

		annotation SummarizationSetBy = Automatic

	column Referee
		dataType: string
		lineageTag: 399512ac-82c7-49e4-9464-3d5e566eff4a
		summarizeBy: none
		sourceColumn: Referee

		annotation SummarizationSetBy = Automatic

	column HS
		dataType: int64
		formatString: 0
		lineageTag: 58a062c0-3a4e-49f1-b86f-85ef994c474f
		summarizeBy: sum
		sourceColumn: HS

		annotation SummarizationSetBy = Automatic

	column AS
		dataType: int64
		formatString: 0
		lineageTag: b354b89e-d2bf-4c51-8c2a-67d52af2ccf3
		summarizeBy: sum
		sourceColumn: AS

		annotation SummarizationSetBy = Automatic

	column HST
		dataType: int64
		formatString: 0
		lineageTag: 796677cc-b95c-466c-a524-17a4e78c7511
		summarizeBy: sum
		sourceColumn: HST

		annotation SummarizationSetBy = Automatic

	column AST
		dataType: int64
		formatString: 0
		lineageTag: 6be5f5b8-1180-433d-a7cb-e17b6bba2252
		summarizeBy: sum
		sourceColumn: AST

		annotation SummarizationSetBy = Automatic

	column HF
		dataType: int64
		formatString: 0
		lineageTag: a224d638-67c0-425c-be34-fc1f914e10c8
		summarizeBy: sum
		sourceColumn: HF

		annotation SummarizationSetBy = Automatic

	column AF
		dataType: int64
		formatString: 0
		lineageTag: 380101a3-fb34-4bc4-81e4-7ab5bb80f7d1
		summarizeBy: sum
		sourceColumn: AF

		annotation SummarizationSetBy = Automatic

	column HC
		dataType: int64
		formatString: 0
		lineageTag: 57bfbbbc-82af-4441-8b59-9cde35ca6277
		summarizeBy: sum
		sourceColumn: HC

		annotation SummarizationSetBy = Automatic

	column AC
		dataType: int64
		formatString: 0
		lineageTag: 68814e90-ae3a-470e-a19d-f58e37c7fccb
		summarizeBy: sum
		sourceColumn: AC

		annotation SummarizationSetBy = Automatic

	column HY
		dataType: int64
		formatString: 0
		lineageTag: d1992f14-ecea-47b3-9a49-92c98498559e
		summarizeBy: sum
		sourceColumn: HY

		annotation SummarizationSetBy = Automatic

	column AY
		dataType: int64
		formatString: 0
		lineageTag: 1a5d6be7-7e54-4486-8762-b4b6996db22b
		summarizeBy: sum
		sourceColumn: AY

		annotation SummarizationSetBy = Automatic

	column HR
		dataType: int64
		formatString: 0
		lineageTag: 725673da-49f0-4a3a-a0c9-ab29102287ec
		summarizeBy: sum
		sourceColumn: HR

		annotation SummarizationSetBy = Automatic

	column AR
		dataType: int64
		formatString: 0
		lineageTag: 6722c0fa-b637-494e-902a-7889e1d41a1e
		summarizeBy: sum
		sourceColumn: AR

		annotation SummarizationSetBy = Automatic

	column Season
		dataType: string
		lineageTag: efc4d491-86c3-4686-bbfe-e9bf688b02c4
		summarizeBy: none
		sourceColumn: Season

		annotation SummarizationSetBy = Automatic

	partition Matches = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\vakom\OneDrive\Desktop\matches_combined.csv"), [Delimiter = ",", Columns = 23, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers",{{"Date", type date}, {"HomeTeam", type text}, {"AwayTeam", type text}, {"FTHG", Int64.Type}, {"FTAG", Int64.Type}, {"FTR", type text}, {"HTHG", Int64.Type}, {"HTAG", Int64.Type}, {"HTR", type text}, {"Referee", type text}, {"HS", Int64.Type}, {"AS", Int64.Type}, {"HST", Int64.Type}, {"AST", Int64.Type}, {"HF", Int64.Type}, {"AF", Int64.Type}, {"HC", Int64.Type}, {"AC", Int64.Type}, {"HY", Int64.Type}, {"AY", Int64.Type}, {"HR", Int64.Type}, {"AR", Int64.Type}, {"Season", type text}})
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

