table Team_Matches
	lineageTag: 13082671-1e82-44ad-8026-08d2ef17dde2

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 75b97b8d-9daa-4c2a-b288-53fbbbe3ffd5
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: ce9ffe01-75cf-420d-bd9d-7ebee95ca2df
			defaultHierarchy: LocalDateTable_991cae14-e277-4b60-8b7d-3a19f33116e4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Season
		dataType: string
		lineageTag: fcc477f1-09b9-4ecf-97cf-8c53b4a32735
		summarizeBy: none
		sourceColumn: Season

		annotation SummarizationSetBy = Automatic

	column Team
		dataType: string
		lineageTag: 8f0c1de7-73e3-4ffa-9cad-868724c20417
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

	column Opponent
		dataType: string
		lineageTag: 67d6d194-74b8-42b8-8eeb-1dc6e22f8b20
		summarizeBy: none
		sourceColumn: Opponent

		annotation SummarizationSetBy = Automatic

	column GoalsFor
		dataType: int64
		formatString: 0
		lineageTag: aefb1232-c991-4744-8aad-dbde93d2b144
		summarizeBy: sum
		sourceColumn: GoalsFor

		annotation SummarizationSetBy = Automatic

	column GoalsAgainst
		dataType: int64
		formatString: 0
		lineageTag: d57d7d2b-d821-4151-bfae-64c965f11256
		summarizeBy: sum
		sourceColumn: GoalsAgainst

		annotation SummarizationSetBy = Automatic

	column ShotsFor
		dataType: int64
		formatString: 0
		lineageTag: 099e87da-7f2f-4d83-a0a9-e7346dc55146
		summarizeBy: sum
		sourceColumn: ShotsFor

		annotation SummarizationSetBy = Automatic

	column ShotsAgainst
		dataType: int64
		formatString: 0
		lineageTag: ffdd6a87-15c0-4290-9703-bf9b9ef25fb3
		summarizeBy: sum
		sourceColumn: ShotsAgainst

		annotation SummarizationSetBy = Automatic

	column ShotsOnTargetFor
		dataType: int64
		formatString: 0
		lineageTag: 9279eebe-1fff-41ea-ac06-04fc261a0116
		summarizeBy: sum
		sourceColumn: ShotsOnTargetFor

		annotation SummarizationSetBy = Automatic

	column ShotsOnTargetAgainst
		dataType: int64
		formatString: 0
		lineageTag: 768efe40-5c0b-4196-ab55-bec0db9aabb4
		summarizeBy: sum
		sourceColumn: ShotsOnTargetAgainst

		annotation SummarizationSetBy = Automatic

	column FoulsFor
		dataType: int64
		formatString: 0
		lineageTag: d1d7b593-1f0c-49e9-b9b7-ae3439521388
		summarizeBy: sum
		sourceColumn: FoulsFor

		annotation SummarizationSetBy = Automatic

	column FoulsAgainst
		dataType: int64
		formatString: 0
		lineageTag: a5be7ea4-2d13-4f17-8a18-b4220a8b0611
		summarizeBy: sum
		sourceColumn: FoulsAgainst

		annotation SummarizationSetBy = Automatic

	column CornersFor
		dataType: int64
		formatString: 0
		lineageTag: b126d5d5-df1d-49c0-a7ed-e7a152aadc59
		summarizeBy: sum
		sourceColumn: CornersFor

		annotation SummarizationSetBy = Automatic

	column CornersAgainst
		dataType: int64
		formatString: 0
		lineageTag: 8ac2928b-5782-4869-9847-d42ab12a8f97
		summarizeBy: sum
		sourceColumn: CornersAgainst

		annotation SummarizationSetBy = Automatic

	column YellowsFor
		dataType: int64
		formatString: 0
		lineageTag: 61410b8c-da0f-4c22-9e0e-482e9cd7dfe5
		summarizeBy: sum
		sourceColumn: YellowsFor

		annotation SummarizationSetBy = Automatic

	column YellowsAgainst
		dataType: int64
		formatString: 0
		lineageTag: 0cc338c7-d123-4c09-8eb6-7b58e8f5088a
		summarizeBy: sum
		sourceColumn: YellowsAgainst

		annotation SummarizationSetBy = Automatic

	column RedsFor
		dataType: int64
		formatString: 0
		lineageTag: 35e45314-c28a-4e53-adc6-09bdda07adac
		summarizeBy: sum
		sourceColumn: RedsFor

		annotation SummarizationSetBy = Automatic

	column RedsAgainst
		dataType: int64
		formatString: 0
		lineageTag: 0d876d3f-a589-4c5f-b897-2dafaa3fa084
		summarizeBy: sum
		sourceColumn: RedsAgainst

		annotation SummarizationSetBy = Automatic

	column IsHome
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4ac39d48-f21b-4512-9261-6b24a3fee47a
		summarizeBy: none
		sourceColumn: IsHome

		annotation SummarizationSetBy = Automatic

	column Result
		dataType: string
		lineageTag: 19df4332-9f7a-447a-b0e7-e733f6541c0e
		summarizeBy: none
		sourceColumn: Result

		annotation SummarizationSetBy = Automatic

	column Points
		dataType: int64
		formatString: 0
		lineageTag: 8f7e7fb4-8cc4-4510-8c3c-62a1ad3bfa8a
		summarizeBy: sum
		sourceColumn: Points

		annotation SummarizationSetBy = Automatic

	column 'Match Number' =
			
			RANKX(
			    FILTER(
			        Team_Matches,
			        Team_Matches[Team] = EARLIER(Team_Matches[Team])
			    ),
			    Team_Matches[Date],
			    ,
			    ASC,
			    Dense
			)
		formatString: 0
		lineageTag: 8ce36d6d-d018-48a2-9be8-525d92eb2d31
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Match Number In Season' =
			
			RANKX(
			    FILTER(
			        Team_Matches,
			        Team_Matches[Team] = EARLIER(Team_Matches[Team])
			            && Team_Matches[Season] = EARLIER(Team_Matches[Season])
			    ),
			    Team_Matches[Date],
			    ,
			    ASC,
			    Dense
			)
		formatString: 0
		lineageTag: c7d2941e-a693-46fa-ad93-62c365772f50
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Team_Matches = m
		mode: import
		source = ```
				let
				    Source = Matches,
				
				    // Home team's perspective
				    HomeRows = Table.SelectColumns(Source, 
				        {"Date","Season","HomeTeam","AwayTeam","FTHG","FTAG","HS","AS","HST","AST","HF","AF","HC","AC","HY","AY","HR","AR"}),
				    HomeRenamed = Table.RenameColumns(HomeRows, {
				        {"HomeTeam","Team"}, {"AwayTeam","Opponent"},
				        {"FTHG","GoalsFor"}, {"FTAG","GoalsAgainst"},
				        {"HS","ShotsFor"}, {"AS","ShotsAgainst"},
				        {"HST","ShotsOnTargetFor"}, {"AST","ShotsOnTargetAgainst"},
				        {"HF","FoulsFor"}, {"AF","FoulsAgainst"},
				        {"HC","CornersFor"}, {"AC","CornersAgainst"},
				        {"HY","YellowsFor"}, {"AY","YellowsAgainst"},
				        {"HR","RedsFor"}, {"AR","RedsAgainst"}
				    }),
				    HomeTagged = Table.AddColumn(HomeRenamed, "IsHome", each true, type logical),
				
				    // Away team's perspective
				    AwayRows = Table.SelectColumns(Source, 
				        {"Date","Season","HomeTeam","AwayTeam","FTHG","FTAG","HS","AS","HST","AST","HF","AF","HC","AC","HY","AY","HR","AR"}),
				    AwayRenamed = Table.RenameColumns(AwayRows, {
				        {"AwayTeam","Team"}, {"HomeTeam","Opponent"},
				        {"FTAG","GoalsFor"}, {"FTHG","GoalsAgainst"},
				        {"AS","ShotsFor"}, {"HS","ShotsAgainst"},
				        {"AST","ShotsOnTargetFor"}, {"HST","ShotsOnTargetAgainst"},
				        {"AF","FoulsFor"}, {"HF","FoulsAgainst"},
				        {"AC","CornersFor"}, {"HC","CornersAgainst"},
				        {"AY","YellowsFor"}, {"HY","YellowsAgainst"},
				        {"AR","RedsFor"}, {"HR","RedsAgainst"}
				    }),
				    AwayTagged = Table.AddColumn(AwayRenamed, "IsHome", each false, type logical),
				
				    // Combine both perspectives
				    Combined = Table.Combine({HomeTagged, AwayTagged}),
				
				    // Add Result (W/D/L) from each team's own perspective
				    AddResult = Table.AddColumn(Combined, "Result", each
				        if [GoalsFor] > [GoalsAgainst] then "W"
				        else if [GoalsFor] < [GoalsAgainst] then "L"
				        else "D", type text
				    ),
				
				    // Add Points (3/1/0) — useful for rolling form later
				    AddPoints = Table.AddColumn(AddResult, "Points", each
				        if [Result] = "W" then 3
				        else if [Result] = "D" then 1
				        else 0, Int64.Type
				    ),
				
				    Sorted = Table.Sort(AddPoints, {{"Team", Order.Ascending}, {"Date", Order.Ascending}}),
				    #"Changed Type" = Table.TransformColumnTypes(Sorted,{{"Season", type text}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

